apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  ports:
  - port: 31005
    nodePort: 31001
    targetPort: myappport
    protocol: TCP
  selector:
    app: nginx-app
  type: NodePort
